let csrf='',busy=false;
const $=id=>document.getElementById(id);
async function api(url,method='GET',data){const r=await fetch(url,{method,headers:{'content-type':'application/json','x-csrf-token':csrf},body:data?JSON.stringify(data):undefined,cache:'no-store'});let x=await r.json();if(!r.ok)throw Error(x.error||'Ошибка запроса');return x}
function notify(s){$('message').textContent=s;setTimeout(()=>{if($('message').textContent===s)$('message').textContent=''},6000)}
function render(data){$('current').textContent=data.current?'В эфире: '+data.current:'Нет подтверждённых активных эфиров';$('meta').textContent='Последняя проверка: '+(data.lastPoll?new Date(data.lastPoll).toLocaleString('ru-RU'):'ещё не выполнялась')+(data.lastError?' · '+data.lastError:'');$('channels').replaceChildren();for(const [i,c] of data.channels.entries()){const row=document.createElement('div');row.className='row';const first=document.createElement('div');const name=document.createElement('a');name.textContent=''+(i+1)+'. '+c.slug;name.href='https://kick.com/'+encodeURIComponent(c.slug);name.target='_blank';name.rel='noopener noreferrer';const badge=document.createElement('span');badge.className='tag '+(c.status==='live'?'live':c.status==='offline'?'offline':'unknown');badge.textContent=!c.enabled?'Отключён':c.status==='live'?'В эфире':c.status==='offline'?'Офлайн':c.error?'Ошибка проверки':'Неизвестно';first.append(name,' ',badge);const controls=document.createElement('div');controls.className='flex';for(const [label,action,extra] of [['↑','move',-1],['↓','move',1],[c.enabled?'Остановить':'Включить','toggle'],['Удалить','remove']]){const b=document.createElement('button');b.textContent=label;b.className=action==='remove'?'danger':'alt';b.title=label+' канал';b.addEventListener('click',()=>modify({action,slug:c.slug,direction:extra}));controls.append(b)}row.append(first,controls);$('channels').append(row)}$('stats').textContent='RAM процесса: '+data.rssMb+' МБ · Время работы: '+Math.floor(data.uptimeMs/60000)+' мин · Постоянное сохранение: '+(data.persistent?'подключено':'не настроено')+' · Kick API: '+(data.apiReady?'настроен':'не настроен');$('events').textContent=data.events.map(x=>new Date(x.at).toLocaleString('ru-RU')+' — '+x.message).join('\n')||'Событий пока нет'}
async function update(){try{render(await api('/api/state'))}catch(e){notify(e.message)}}
async function modify(x){if(busy)return;busy=true;try{render(await api('/api/channels','POST',x))}catch(e){notify(e.message)}finally{busy=false}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const a=await api('/api/login','POST',{password:$('password').value});csrf=a.csrf;$('password').value='';$('login').style.display='none';$('app').style.display='block';await update()}catch(e){$('loginError').textContent=e.message}});
$('addForm').addEventListener('submit',async e=>{e.preventDefault();await modify({action:'add',slug:$('channel').value});$('channel').value=''});
$('refresh').addEventListener('click',async()=>{try{render(await api('/api/poll','POST'));notify('Проверка завершена')}catch(e){notify(e.message)}});
$('logout').addEventListener('click',async()=>{await api('/api/logout','POST');location.reload()});
(async()=>{try{const s=await api('/api/session');if(s.authenticated){csrf=s.csrf;$('login').style.display='none';$('app').style.display='block';await update()}}catch{}})();setInterval(()=>{if(csrf)update()},20000);
