'use strict';
let csrf='',busy=false,dataCache=null;
const $=id=>document.getElementById(id);
const fmtDate=x=>x?new Date(x).toLocaleString('ru-RU'):'Нет данных';
const duration=ms=>{if(!Number.isFinite(ms)||ms<0)return 'Нет данных';const s=Math.floor(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return (d?d+' д ':'')+(h?h+' ч ':'')+m+' мин'};
const statusText=c=>!c.enabled?'Остановлен':({live:'В эфире',offline:'Офлайн',paused:'Остановлен',unknown:c.error?'Ошибка проверки':'Неизвестно'})[c.status]||'Неизвестно';
const statusClass=c=>!c.enabled?'paused':c.status==='unknown'?'unknown':c.status;
function el(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}
function notify(msg){$('message').textContent=msg;setTimeout(()=>{if($('message').textContent===msg)$('message').textContent=''},6500)}
async function api(url,method='GET',payload){const r=await fetch(url,{method,headers:{'content-type':'application/json','x-csrf-token':csrf},body:payload?JSON.stringify(payload):undefined,cache:'no-store'});let x=await r.json();if(!r.ok)throw Error(x.error||'Ошибка запроса');return x}
function stat(label,value){const box=el('div','stat');box.append(el('div','sub',label),el('strong','',String(value)));return box}
function badge(c){return el('span','badge '+statusClass(c),statusText(c))}
function drawCard(c,index,controls){const item=el('article','channel '+statusClass(c));const head=el('div','row');const left=el('div');const a=el('a','name',c.slug);a.href='https://kick.com/'+encodeURIComponent(c.slug);a.target='_blank';a.rel='noopener noreferrer';left.append(a,el('div','sub','Приоритет: '+(index+1)));head.append(left,badge(c));item.append(head);const details=el('div','small muted');details.style.marginTop='12px';details.append(el('div','', 'Последняя проверка: '+fmtDate(c.checkedAt)),el('div','', 'Время эфира: '+(c.status==='live'&&c.liveSince?duration(Date.now()-Date.parse(c.liveSince)):'Нет подтверждённых данных')));if(c.error)details.append(el('div','',c.error));item.append(details);if(controls){const row=el('div','controls');for(const [title,action,direction] of [['↑','move',-1],['↓','move',1],[c.enabled?'Приостановить мониторинг':'Возобновить мониторинг','toggle',null],['Удалить','remove',null]]){const button=el('button',action==='remove'?'danger':'',title);button.title=action==='toggle'?'Отключает или включает проверку эфира через API. Не управляет воспроизведением видео.':title;button.addEventListener('click',()=>{if(action==='remove'&&!confirm('Удалить канал '+c.slug+'?'))return;modify({action,slug:c.slug,direction})});row.append(button)}item.append(row)}return item}
function metric(parent,label,value){const row=el('div','metric');row.append(el('span','muted',label),el('span','',String(value)));parent.append(row)}
function render(d){dataCache=d;updateWatchChannels(d);const chosen=d.channels.find(c=>c.slug===d.current);$('current').textContent=chosen?'Выбран эфир: '+chosen.slug:'Нет выбранного прямого эфира';$('meta').textContent='Последняя проверка: '+fmtDate(d.lastPoll)+(d.lastError?' · '+d.lastError:'');$('topState').textContent=d.lastError?'Ошибка проверки эфиров':d.apiReady?'API подключён':'API не настроен';$('topState').className='badge '+(d.lastError?'error':d.apiReady?'live':'unknown');$('quickStats').replaceChildren(stat('Каналов в эфире',d.channels.filter(x=>x.status==='live'&&x.enabled).length),stat('Всего каналов',d.channels.length),stat('Работа сервера',duration(d.uptimeMs)));$('channels').replaceChildren();$('summaryChannels').replaceChildren();d.channels.forEach((c,i)=>{$('channels').append(drawCard(c,i,true));$('summaryChannels').append(drawCard(c,i,false))});if(!d.channels.length){$('channels').append(el('p','muted','Каналы пока не добавлены'));$('summaryChannels').append(el('p','muted','Каналов нет'))}
const acct=$('kickAccounts');acct.replaceChildren();for(const a of d.accounts||[]){const card=el('article','channel');card.append(el('h3','',a.name),el('div','sub','Профиль подтверждён через Kick OAuth'),el('p','muted small','Подключён: '+fmtDate(a.addedAt)),el('p','muted small','Просмотр видео: не выполняется'));const btn=el('button','danger','Отключить профиль');btn.addEventListener('click',async()=>{if(!confirm('Отключить профиль '+a.name+'?'))return;try{render(await api('/api/accounts/remove','POST',{id:a.id}))}catch(e){notify(e.message)}});card.append(btn);acct.append(card)}if(!d.accounts?.length)acct.append(el('p','muted','Профили Kick пока не подключены. Нажми кнопку выше и подтверди доступ на Kick.'));
const m=d.server||{},memory=$('memorySummary');memory.replaceChildren(stat('RAM процесса (RSS)',(m.rssMb??'—')+' МБ'),stat('Память контейнера',m.containerMb==null?'Недоступна':m.containerMb+' МБ'),stat('Использовано JS heap',(m.heapUsedMb??'—')+' МБ'));const det=$('details');det.replaceChildren();for(const [key,value] of [['Всего JS heap',(m.heapTotalMb??'—')+' МБ'],['Внешняя память',(m.externalMb??'—')+' МБ'],['ArrayBuffers',(m.arrayBuffersMb??'—')+' МБ'],['Лимит памяти (ориентир)',(m.memoryLimitMb??'—')+' МБ'],['Версия Node.js',m.node||'—'],['Запущен',fmtDate(d.bootAt)],['Время работы',duration(d.uptimeMs)],['Проверок API',d.checks??0],['Ошибок API',d.failures??0],['Последний успешный ответ',fmtDate(d.lastSuccess)],['Supabase',d.persistent?(d.storageError?'Ошибка: '+d.storageError:'Подключён'):'Не подключён'],['Последнее сохранение',fmtDate(d.lastStoredAt)],['Kick API',d.apiReady?'Настроен':'Не настроен']])metric(det,key,value);$('securityInfo').textContent='Источник пароля: '+(d.passwordSource==='Supabase'?'Supabase':'Render')+'. Постоянное хранилище: '+(d.persistent?'подключено':'не подключено');const journal=$('events');journal.replaceChildren();for(const x of d.events||[])journal.append(el('div','log',fmtDate(x.at)+' · '+x.message));if(!d.events?.length)journal.append(el('p','muted','Событий пока нет'))}
async function update(){try{render(await api('/api/state'))}catch(e){notify(e.message)}}
async function modify(x){if(busy)return;busy=true;try{render(await api('/api/channels','POST',x))}catch(e){notify(e.message)}finally{busy=false}}
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('on',x.id==='view-'+b.dataset.tab))});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const x=await api('/api/login','POST',{password:$('password').value});csrf=x.csrf;$('password').value='';$('login').classList.add('hidden');$('app').style.display='block';await update()}catch(e){$('loginError').textContent=e.message}});
$('addForm').addEventListener('submit',async e=>{e.preventDefault();const value=$('channel').value;await modify({action:'add',slug:value});$('channel').value=''});
$('refresh').addEventListener('click',async()=>{try{render(await api('/api/poll','POST'));notify('Статусы включённых каналов обновлены через Kick API. Просмотр аккаунтов не запускался.')}catch(e){notify(e.message)}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout','POST')}finally{location.reload()}});
$('passwordForm').addEventListener('submit',async e=>{e.preventDefault();const n=$('newPassword').value;if(n!==$('newPassword2').value){notify('Новые пароли не совпадают');return}try{await api('/api/password','POST',{currentPassword:$('oldPassword').value,newPassword:n});alert('Пароль изменён. Войдите с новым паролем.');location.reload()}catch(e){notify(e.message)}});
(async()=>{try{const s=await api('/api/session');if(s.authenticated){csrf=s.csrf;$('login').classList.add('hidden');$('app').style.display='block';await update()}}catch{}})();setInterval(()=>{if(csrf)void update()},20000);

$('connectKick').addEventListener('click',async()=>{try{const r=await api('/api/oauth/start','POST',{});location.assign(r.url)}catch(e){notify(e.message)}});
const oauthStatus=new URLSearchParams(location.search).get('oauth');if(oauthStatus){$('oauthMessage').textContent=({success:'Профиль Kick успешно подключён.',denied:'Подключение отменено.',failed:'Подключение не удалось. Проверь Redirect URL в Kick.',expired:'Подключение устарело. Начни заново.'})[oauthStatus]||'';history.replaceState(null,'',location.pathname);}

// User-initiated official Kick embedded player; never starts on the server or by OAuth.
let playingSlug='',openedAt=0;
function updateWatchChannels(d){const sel=$('watchChannel');const old=sel.value;const names=(d.channels||[]).map(c=>c.slug);sel.replaceChildren();for(const slug of names){const opt=el('option','',slug);opt.value=slug;sel.append(opt)}sel.value=names.includes(old)?old:(names.includes(d.current)?d.current:(names[0]||''));$('startWatching').disabled=!names.length;updateWatchLink()}
function updateWatchLink(){const slug=$('watchChannel').value;$('watchKickLink').href=slug?'https://kick.com/'+encodeURIComponent(slug):'https://kick.com'}
$('watchChannel').addEventListener('change',updateWatchLink);
$('startWatching').addEventListener('click',()=>{const slug=$('watchChannel').value;if(!/^[a-zA-Z0-9_-]{1,35}$/.test(slug)){notify('Некорректный адрес канала');return}stopPlayer();const iframe=document.createElement('iframe');iframe.title='Официальный плеер Kick: '+slug;iframe.src='https://player.kick.com/'+encodeURIComponent(slug)+'?autoplay=true&muted=false';iframe.allow='autoplay; fullscreen; picture-in-picture';iframe.setAttribute('allowfullscreen','');iframe.referrerPolicy='strict-origin-when-cross-origin';$('playerSlot').replaceChildren(iframe);playingSlug=slug;openedAt=Date.now();$('playerStatus').textContent='Открыт в браузере';$('playerChannel').textContent=slug;$('stopWatching').disabled=false;$('playerNotice').textContent='Плеер Kick открыт в твоём браузере. Если Kick не разрешил автоматический запуск, нажми Play внутри плеера. Статус воспроизведения и начисление наград серверу недоступны.';updatePlayerElapsed()});
function stopPlayer(){playingSlug='';openedAt=0;$('playerSlot').replaceChildren(el('div','muted','Просмотр остановлен.'));$('playerStatus').textContent='Остановлен';$('playerChannel').textContent='—';$('playerElapsed').textContent='—';$('stopWatching').disabled=true;$('playerNotice').textContent='Плеер остановлен и удалён из страницы.'}
$('stopWatching').addEventListener('click',stopPlayer);
function updatePlayerElapsed(){if(openedAt)$('playerElapsed').textContent=duration(Date.now()-openedAt)}
setInterval(updatePlayerElapsed,1000);
