import http from 'node:http';
import {randomBytes,createHmac,timingSafeEqual,scryptSync,createCipheriv,createDecipheriv,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';

const PORT=Number(process.env.PORT||10000);
const PASSWORD=process.env.ADMIN_PASSWORD||'';
const SECRET=process.env.SESSION_SECRET||'';
const KID=process.env.KICK_CLIENT_ID||'';
const KSECRET=process.env.KICK_CLIENT_SECRET||'';
const BASE_URL=(process.env.RENDER_EXTERNAL_URL||'https://cytophage.onrender.com').replace(/\/$/,'');
const REDIRECT_URI=BASE_URL+'/';
const DBURL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const DBKEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const POLL_MS=90000, MAX_CHANNELS=30;
if(!PASSWORD||!SECRET||SECRET.length<32) {console.error('Настройте ADMIN_PASSWORD и SESSION_SECRET (не менее 32 символов) в Render.');process.exit(1)}
const passwordSalt=createHmac('sha256',SECRET).update('password-salt').digest().subarray(0,16);
let passwordHash=scryptSync(PASSWORD,passwordSalt,64);
let passwordSource='Render';
const sessions=new Map(); const loginAttempts=new Map();
let monitoringEnabled=true,channels=[],current=null,lastPoll=0,lastError='',busy=false,boot=Date.now(),token=null,expires=0;
let lastSuccess=0,checks=0,failures=0,storageError='',lastStoredAt=null,authLoaded=false;
const events=[];
const oauthPending=new Map();
let accounts=[];
const TOKEN_KEY=createHash('sha256').update('kick-accounts:v1:').update(SECRET).digest();
function encrypt(obj){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',TOKEN_KEY,iv);const data=Buffer.concat([c.update(JSON.stringify(obj),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),data.toString('base64url')].join('.');}
function decrypt(value){const [i,t,d]=value.split('.');const c=createDecipheriv('aes-256-gcm',TOKEN_KEY,Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return JSON.parse(Buffer.concat([c.update(Buffer.from(d,'base64url')),c.final()]).toString());}
function accountsPublic(){return accounts.map(x=>({id:x.id,name:x.name,addedAt:x.addedAt,status:x.status||'connected'}));}
async function persistAccounts(){if(!DBURL||!DBKEY)throw Error('Для подключения аккаунтов необходимо постоянное хранилище Supabase');const r=await fetch(`${DBURL}/rest/v1/cytophage_world?on_conflict=id`,{method:'POST',headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`,'content-type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'kick_monitor_accounts',payload:{version:1,accounts:accounts.map(x=>({id:x.id,name:x.name,addedAt:x.addedAt,encrypted:encrypt(x.tokens)}))},updated_at:new Date().toISOString()}),signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error('Не удалось сохранить аккаунты в Supabase: '+r.status)}
async function loadAccounts(){if(!DBURL||!DBKEY)return;const r=await fetch(`${DBURL}/rest/v1/cytophage_world?id=eq.kick_monitor_accounts&select=payload`,{headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error('Не удалось загрузить аккаунты: '+r.status);const rows=await r.json();accounts=(rows?.[0]?.payload?.accounts||[]).slice(0,10).map(x=>({id:String(x.id),name:String(x.name),addedAt:x.addedAt,tokens:decrypt(x.encrypted),status:'connected'}))}
function cleanupOauth(){for(const [k,v] of oauthPending)if(v.until<Date.now())oauthPending.delete(k);while(oauthPending.size>20)oauthPending.delete(oauthPending.keys().next().value)}
async function kickTokenRequest(params){const r=await fetch('https://id.kick.com/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params),signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Авторизация Kick: HTTP '+r.status);return r.json()}
async function kickIdentity(access){const r=await fetch('https://api.kick.com/public/v1/users',{headers:{Authorization:'Bearer '+access,Accept:'application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Не удалось получить профиль Kick: HTTP '+r.status);const result=await r.json();const user=result.data?.[0]||result.data;if(!user||!user.user_id||!user.name)throw Error('Kick не вернул ID и имя профиля');return {id:String(user.user_id),name:String(user.name)}}
function redirect(res,path){res.writeHead(302,{location:path,'cache-control':'no-store'});res.end()}

function log(message){events.unshift({at:new Date().toISOString(),message});events.length=Math.min(events.length,200);console.log('[Kick Monitor]',message)}
function safeMessage(e){const s=String(e?.message||e);return s.replace(/Bearer\s+\S+/gi,'Bearer [скрыто]').slice(0,180)}
function parseSlug(value){let s=String(value||'').trim();try{const url=new URL(s);if(!['kick.com','www.kick.com'].includes(url.hostname))throw Error('Нужна ссылка Kick');s=url.pathname.split('/').filter(Boolean)[0]||''}catch(e){if(s.includes('://'))throw e}if(!/^[a-z0-9_-]{2,25}$/i.test(s))throw Error('Укажите корректный канал Kick');return s.toLowerCase()}
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(obj))}
async function body(req){let chunks=[],size=0;for await(const b of req){size+=b.length;if(size>16000)throw Error('Слишком большой запрос');chunks.push(b)}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}
function cookies(req){const m=Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=').slice(0,2)));return m}
function authenticated(req){const sid=cookies(req).sid;if(!sid||!sessions.has(sid))return false;const item=sessions.get(sid);if(item.expires<Date.now()){sessions.delete(sid);return false}return true}
function csrf(req){const sid=cookies(req).sid;return authenticated(req) && req.headers['x-csrf-token']===sessions.get(sid).csrf}
function requestIsHttps(req){return req.headers['x-forwarded-proto']==='https'}
function sessionCookie(value,req,maxAge){return `sid=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}; ${requestIsHttps(req)?'Secure; ':''}`}
function pruneSessions(){for(const [k,v] of sessions)if(v.expires<Date.now())sessions.delete(k);while(sessions.size>40)sessions.delete(sessions.keys().next().value);for(const [k,v] of loginAttempts)if(v.until<Date.now()-3600000)loginAttempts.delete(k)}
function mb(x){return Math.round(x/1048576*10)/10}
function state(){const m=process.memoryUsage();const total=Number(process.env.RENDER_MEMORY_LIMIT_MB)||512;let containerMb=null;try{const value=Number(readCgroup());if(Number.isFinite(value)&&value>0)containerMb=mb(value)}catch{}return {monitoringEnabled,channels,current,lastPoll,lastSuccess,lastError,checks,failures,events,uptimeMs:Date.now()-boot,bootAt:new Date(boot).toISOString(),server:{rssMb:mb(m.rss),heapUsedMb:mb(m.heapUsed),heapTotalMb:mb(m.heapTotal),externalMb:mb(m.external),arrayBuffersMb:mb(m.arrayBuffers||0),containerMb,memoryLimitMb:total,node:process.version,pid:process.pid,platform:process.platform},persistent:!!(DBURL&&DBKEY),storageError,lastStoredAt,apiReady:!!(KID&&KSECRET),passwordSource,accounts:accountsPublic(),viewerPlaybackCount:0,confirmedWatchTime:null}}
function readCgroup(){return requireCgroupValue()}
function requireCgroupValue(){try{return Number(requireCgroupCache())}catch{return NaN}}
function requireCgroupCache(){return cgroupUsage}
let cgroupUsage=NaN;
async function refreshCgroup(){try{const t=await readFile('/sys/fs/cgroup/memory.current','utf8');cgroupUsage=Number(t.trim())}catch{try{const t=await readFile('/sys/fs/cgroup/memory/memory.usage_in_bytes','utf8');cgroupUsage=Number(t.trim())}catch{cgroupUsage=NaN}}}

async function save(){if(!DBURL||!DBKEY)return;const r=await fetch(`${DBURL}/rest/v1/cytophage_world?on_conflict=id`,{method:'POST',headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`,'content-type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'kick_monitor',payload:{monitoringEnabled,channels:channels.map(({slug,enabled})=>({slug,enabled}))},updated_at:new Date().toISOString()}),signal:AbortSignal.timeout(9000)});if(!r.ok){storageError=`HTTP ${r.status}`;throw Error(`Ошибка сохранения (${r.status})`)}storageError='';lastStoredAt=new Date().toISOString()}
async function load(){if(!DBURL||!DBKEY)return;try{const r=await fetch(`${DBURL}/rest/v1/cytophage_world?id=eq.kick_monitor&select=payload`,{headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(`Код ${r.status}`);const rows=await r.json();if(typeof rows[0]?.payload?.monitoringEnabled==='boolean')monitoringEnabled=rows[0].payload.monitoringEnabled;if(Array.isArray(rows[0]?.payload?.channels))channels=rows[0].payload.channels.slice(0,MAX_CHANNELS).map(x=>({slug:parseSlug(x.slug),enabled:x.enabled!==false,status:'unknown',checkedAt:null,error:''}));log('Каналы загружены из Supabase')}catch(e){log('Не удалось загрузить каналы: '+safeMessage(e))}}
async function loadPassword(){if(!DBURL||!DBKEY)return;try{const r=await fetch(`${DBURL}/rest/v1/cytophage_world?id=eq.kick_monitor_auth&select=payload`,{headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const a=await r.json();const v=a?.[0]?.payload;if(v?.salt&&v?.hash&&/^[a-f0-9]{32}$/.test(v.salt)&&/^[a-f0-9]{128}$/.test(v.hash)){passwordHash=Buffer.from(v.hash,'hex');activeSalt=Buffer.from(v.salt,'hex');passwordSource='Supabase'}authLoaded=true}catch(e){log('Ошибка загрузки пароля: '+safeMessage(e));throw Error('Не удалось проверить пароль администратора в Supabase')}}
async function changePassword(oldPassword,newPassword){if(!DBURL||!DBKEY)throw Error('Для смены пароля из панели требуется Supabase');if(typeof newPassword!=='string'||newPassword.length<12||newPassword.length>128)throw Error('Новый пароль должен содержать 12–128 символов');if(!checkPassword(oldPassword))throw Error('Текущий пароль неверен');const salt=randomBytes(16),hash=scryptSync(newPassword,salt,64);const r=await fetch(`${DBURL}/rest/v1/cytophage_world?on_conflict=id`,{method:'POST',headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`,'content-type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'kick_monitor_auth',payload:{salt:salt.toString('hex'),hash:hash.toString('hex')},updated_at:new Date().toISOString()}),signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(`Не удалось сохранить пароль: HTTP ${r.status}`);passwordHash=hash;passwordSource='Supabase';sessions.clear();log('Пароль администратора изменён (все сессии закрыты)')}
function checkPassword(s){if(typeof s!=='string'||s.length>256)return false;const salt=passwordSource==='Supabase'?activeSalt:passwordSalt;return timingSafeEqual(scryptSync(s,salt,64),passwordHash)}
let activeSalt=passwordSalt;
async function appToken(){if(!KID||!KSECRET)throw Error('Добавьте KICK_CLIENT_ID и KICK_CLIENT_SECRET в Render');if(token&&Date.now()<expires-60000)return token;const r=await fetch('https://id.kick.com/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',client_id:KID,client_secret:KSECRET}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error(`Kick OAuth: код ${r.status}`);const d=await r.json();if(!d.access_token)throw Error('Kick OAuth не вернул токен');token=d.access_token;expires=Date.now()+Math.max(120,Number(d.expires_in)||3600)*1000;return token}
async function poll(){if(busy)return;busy=true;try{const active=channels.filter(c=>c.enabled);if(!monitoringEnabled){current=null;lastError='';return}if(!active.length){current=null;lastError='';return}const key=await appToken();const q=new URLSearchParams();for(const c of active)q.append('slug',c.slug);const r=await fetch(`https://api.kick.com/public/v1/channels?${q}`,{headers:{Authorization:`Bearer ${key}`,Accept:'application/json'},signal:AbortSignal.timeout(12000)});if(r.status===401){token=null;expires=0}if(!r.ok)throw Error(`Kick API: код ${r.status}`);const data=(await r.json()).data;if(!Array.isArray(data))throw Error('Неизвестный формат ответа Kick');const found=new Map(data.map(x=>[String(x.slug||'').toLowerCase(),x]));for(const c of channels){if(!c.enabled){c.status='paused';continue}const d=found.get(c.slug);c.status=!d?'unknown':d.stream?.is_live===true?'live':d.stream?.is_live===false?'offline':d.stream&&Object.keys(d.stream).length>0?'live':'offline';c.checkedAt=new Date().toISOString();c.liveSince=c.status==='live'?(d.stream?.start_time||d.stream?.started_at||null):null;c.error=!d?'Канал не найден в ответе API':''}const before=current;current=active.find(c=>c.status==='live')?.slug||null;if(current!==before)log(current?`Выбран канал: ${current}`:'Активных эфиров нет');lastError='';lastSuccess=Date.now();checks++}catch(e){failures++;lastError=safeMessage(e);for(const c of channels)if(c.enabled){c.status='unknown';c.error='Ошибка проверки: статус неизвестен'}log(lastError)}finally{lastPoll=Date.now();busy=false}}
async function change(operation,payload){const before=JSON.stringify(channels);if(operation==='add'){const slug=parseSlug(payload.slug);if(channels.some(c=>c.slug===slug))throw Error('Канал уже добавлен');if(channels.length>=MAX_CHANNELS)throw Error('Достигнут лимит каналов');channels.push({slug,enabled:true,status:'unknown',checkedAt:null,error:''})}else if(operation==='remove'){channels=channels.filter(c=>c.slug!==parseSlug(payload.slug))}else if(operation==='toggle'){const c=channels.find(c=>c.slug===parseSlug(payload.slug));if(!c)throw Error('Канал не найден');c.enabled=!c.enabled;c.status='unknown'}else if(operation==='move'){const i=channels.findIndex(c=>c.slug===parseSlug(payload.slug));const to=i+Number(payload.direction);if(i<0||![-1,1].includes(Number(payload.direction))||to<0||to>=channels.length)throw Error('Невозможно переместить');[channels[i],channels[to]]=[channels[to],channels[i]]}else throw Error('Неизвестное действие');try{await save()}catch(e){channels=JSON.parse(before);throw e}void poll()}
await loadPassword();try{await loadAccounts()}catch(e){console.error("Ошибка хранилища аккаунтов:",safeMessage(e));process.exit(1)}await refreshCgroup();setInterval(()=>void refreshCgroup(),15000).unref();
const html=await readFile(new URL('./index.html',import.meta.url),'utf8');
const appJs=await readFile(new URL('./app.js',import.meta.url),'utf8');
const server=http.createServer(async(req,res)=>{try{res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.setHeader('content-security-policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'");const url=new URL(req.url,'http://localhost');if(url.pathname==='/'&&req.method==='GET'&&url.searchParams.has('state')&& (url.searchParams.has('code')||url.searchParams.has('error'))){
 const key=url.searchParams.get('state')||'';const flow=oauthPending.get(key);oauthPending.delete(key);
 if(!flow||flow.until<Date.now()||!sessions.has(flow.sid))return redirect(res,'/?oauth=expired');
 if(url.searchParams.has('error'))return redirect(res,'/?oauth=denied');
 try{const t=await kickTokenRequest({grant_type:'authorization_code',client_id:KID,client_secret:KSECRET,redirect_uri:REDIRECT_URI,code_verifier:flow.verifier,code:url.searchParams.get('code')||''});if(!t.access_token||!t.refresh_token)throw Error('Kick не предоставил пользовательский токен');const identity=await kickIdentity(t.access_token);const entry={...identity,addedAt:new Date().toISOString(),tokens:{access:t.access_token,refresh:t.refresh_token,expires:Date.now()+Number(t.expires_in||3600)*1000},status:'connected'};const old=accounts;accounts=[...accounts.filter(x=>x.id!==entry.id),entry].slice(-10);try{await persistAccounts()}catch(e){accounts=old;throw e}log('Подключён профиль Kick: '+identity.name);return redirect(res,'/?oauth=success')}catch(e){log('Ошибка OAuth: '+safeMessage(e));return redirect(res,'/?oauth=failed')}
}
if(url.pathname==='/app.js'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'});return res.end(appJs)}if(url.pathname==='/health')return json(res,200,{ok:true,uptimeSec:Math.floor((Date.now()-boot)/1000)});if(url.pathname==='/'&&req.method==='GET'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});return res.end(html)}if(url.pathname==='/api/login'&&req.method==='POST'){const addr=req.socket.remoteAddress||'ip';const attempt=loginAttempts.get(addr)||{count:0,until:0};if(attempt.count>=5&&attempt.until>Date.now())return json(res,429,{error:'Слишком много попыток. Подождите 15 минут.'});const data=await body(req);if(!checkPassword(String(data.password||''))){loginAttempts.set(addr,{count:attempt.count+1,until:Date.now()+900000});return json(res,401,{error:'Неверный пароль'})}loginAttempts.delete(addr);pruneSessions();const sid=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(sid,{csrf,expires:Date.now()+8*3600000});res.setHeader('set-cookie',sessionCookie(sid,req,28800));return json(res,200,{ok:true,csrf})}if(url.pathname==='/api/session')return json(res,200,{authenticated:authenticated(req),csrf:authenticated(req)?sessions.get(cookies(req).sid).csrf:null});if(!authenticated(req))return json(res,401,{error:'Войдите в панель'});if(url.pathname==='/api/oauth/start'&&req.method==='POST'){
if(!csrf(req))return json(res,403,{error:'Сессия недействительна'});if(!KID||!KSECRET)return json(res,400,{error:'Kick API не настроен'});if(!DBURL||!DBKEY)return json(res,400,{error:'Supabase не настроен'});cleanupOauth();const stateKey=randomBytes(24).toString('base64url'),verifier=randomBytes(48).toString('base64url');oauthPending.set(stateKey,{sid:cookies(req).sid,verifier,until:Date.now()+600000});const u=new URL('https://id.kick.com/oauth/authorize');for(const [k,v] of Object.entries({response_type:'code',client_id:KID,redirect_uri:REDIRECT_URI,scope:'user:read',code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',state:stateKey}))u.searchParams.set(k,v);return json(res,200,{url:u.toString()})}
if(url.pathname==='/api/state'&&req.method==='GET')return json(res,200,state());if(req.method==='POST'){if(!csrf(req))return json(res,403,{error:'Сессия недействительна'});if(url.pathname==='/api/accounts/remove'){const x=await body(req);const previous=accounts;const a=accounts.find(y=>y.id===String(x.id));if(!a)return json(res,404,{error:'Аккаунт не найден'});accounts=accounts.filter(y=>y.id!==a.id);try{await persistAccounts()}catch(e){accounts=previous;throw e}log('Профиль Kick отключён: '+a.name);return json(res,200,state())}
if(url.pathname==='/api/password'){const input=await body(req);await changePassword(input.currentPassword,input.newPassword);res.setHeader('set-cookie',sessionCookie('',req,0));return json(res,200,{ok:true})}if(url.pathname==='/api/logout'){sessions.delete(cookies(req).sid);res.setHeader('set-cookie',sessionCookie('',req,0));return json(res,200,{ok:true})}if(url.pathname==='/api/poll'){await poll();return json(res,200,state())}if(url.pathname==='/api/monitoring'){const x=await body(req);if(typeof x.enabled!=='boolean')return json(res,400,{error:'Неверный переключатель'});const was=monitoringEnabled;monitoringEnabled=x.enabled;try{await save()}catch(e){monitoringEnabled=was;throw e}log(monitoringEnabled?'Мониторинг включён':'Мониторинг приостановлен');await poll();return json(res,200,state())}if(url.pathname==='/api/channels'){const x=await body(req);await change(x.action,x);return json(res,200,state())}}return json(res,404,{error:'Не найдено'})}catch(e){return json(res,400,{error:safeMessage(e)})}});
server.listen(PORT,'0.0.0.0',()=>log(`HTTP сервер слушает порт ${PORT}`));
await load();void poll();const interval=setInterval(()=>{void poll();pruneSessions();cleanupOauth()},POLL_MS);interval.unref();
process.on('SIGTERM',()=>{clearInterval(interval);server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),10000).unref()});
